/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MroflSpigotWizardSwing1.java
 *
 * Created on 26 oct. 2011, 15:31:48
 */
package com.stanford.mroflspigot.ui;

import com.stanford.mroflspigot.MroflSpigot;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Sébastien Heymann
 */
public class MroflSpigotWizardSwing1 extends javax.swing.JPanel {

    /** Creates new form MroflSpigotWizardSwing1 */
    public MroflSpigotWizardSwing1() {
        initComponents();

        SpinnerModel depthModel = new SpinnerNumberModel(
                1, //initial value
                1, //min
                3, //max
                1); //step
        depthSpinner.setModel(depthModel);
    }

    public void unsetup(MroflSpigot importer) {
        //Configure the importer
        importer.setDepth((Integer) depthSpinner.getValue());
        importer.setNameRaw(nameRawField.getText());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameRawField = new javax.swing.JTextField();
        depthSpinner = new javax.swing.JSpinner();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(MroflSpigotWizardSwing1.class, "MroflSpigotWizardSwing1.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(MroflSpigotWizardSwing1.class, "MroflSpigotWizardSwing1.jLabel2.text")); // NOI18N

        nameRawField.setText(org.openide.util.NbBundle.getMessage(MroflSpigotWizardSwing1.class, "MroflSpigotWizardSwing1.nameRawField.text")); // NOI18N
        nameRawField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameRawFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameRawField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameRawField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(depthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(231, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameRawFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameRawFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameRawFieldActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner depthSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nameRawField;
    // End of variables declaration//GEN-END:variables
}
